export type LocalInvestorProfile = {
  id: string;
  name: string;
  firm: string;
  role: string;
  initials: string;
  color: string;
  location: string;
  geography: "Local" | "Regional" | "Thesis fit";
  stages: string[];
  sectors: string[];
  checkSize: string;
  activity: string;
  thesis: string;
  portfolioSignals: string[];
  contactPath: string;
  sourceLabels: string[];
};

export const localInvestorProfiles: LocalInvestorProfile[] = [
  {
    id: "miami-angels",
    name: "Miami Angels",
    firm: "Miami Angels",
    role: "Angel network",
    initials: "MA",
    color: "#3B4EE8",
    location: "Miami, FL",
    geography: "Local",
    stages: ["Validation / angel", "Pre-seed", "Seed"],
    sectors: ["SaaS", "Marketplace", "Fintech", "Consumer", "Healthcare"],
    checkSize: "$50k-$500k",
    activity: "Local angel network",
    thesis: "Miami-based angel network backing early startups with local investor access.",
    portfolioSignals: ["early-stage rounds", "local operator angels", "community-driven access"],
    contactPath: "Ask for a warm intro through a Miami founder, operator, or Refresh Miami connection.",
    sourceLabels: ["Miami investor network", "Local angel access"],
  },
  {
    id: "florida-funders",
    name: "Florida Funders",
    firm: "Florida Funders",
    role: "Seed investor",
    initials: "FF",
    color: "#12936A",
    location: "Florida",
    geography: "Regional",
    stages: ["Pre-seed", "Seed", "Series A-ready"],
    sectors: ["SaaS", "Healthcare", "Fintech", "Deep tech", "B2B"],
    checkSize: "$250k-$2M",
    activity: "Active Florida seed platform",
    thesis: "Florida-focused venture platform investing across early-stage technology companies.",
    portfolioSignals: ["Florida ecosystem", "B2B software", "seed rounds"],
    contactPath: "Lead with Florida market relevance and ask for the seed investment team.",
    sourceLabels: ["Florida VC", "Seed platform"],
  },
  {
    id: "theventurecity",
    name: "TheVentureCity",
    firm: "TheVentureCity",
    role: "Early-stage fund",
    initials: "TVC",
    color: "#6D5CF0",
    location: "Miami, FL",
    geography: "Local",
    stages: ["Pre-seed", "Seed", "Seed / Series A"],
    sectors: ["SaaS", "Marketplace", "Consumer", "Fintech", "AI"],
    checkSize: "$100k-$1M",
    activity: "Miami-based global fund",
    thesis: "Operator-led early-stage fund with Miami roots and a global software lens.",
    portfolioSignals: ["product-led growth", "international expansion", "operator support"],
    contactPath: "Use the Miami/operator angle and ask for feedback on growth narrative.",
    sourceLabels: ["Miami HQ", "Operator-led fund"],
  },
  {
    id: "fuel-venture-capital",
    name: "Fuel Venture Capital",
    firm: "Fuel Venture Capital",
    role: "Growth-oriented VC",
    initials: "FVC",
    color: "#0E1426",
    location: "Miami, FL",
    geography: "Local",
    stages: ["Seed", "Seed / Series A", "Series A-ready"],
    sectors: ["Fintech", "Enterprise", "Marketplace", "Consumer", "AI"],
    checkSize: "$500k-$5M",
    activity: "Miami venture firm",
    thesis: "Miami venture firm backing high-growth technology companies from early to growth stages.",
    portfolioSignals: ["venture-scale markets", "growth narrative", "Miami ecosystem"],
    contactPath: "Lead with scale signals, round size, and why Miami is a strategic base.",
    sourceLabels: ["Miami VC", "Growth-stage lens"],
  },
  {
    id: "krillion-ventures",
    name: "Krillion Ventures",
    firm: "Krillion Ventures",
    role: "Seed fund",
    initials: "KV",
    color: "#2BB6E8",
    location: "Miami, FL",
    geography: "Local",
    stages: ["Pre-seed", "Seed"],
    sectors: ["SaaS", "Fintech", "Healthcare", "Consumer", "Proptech"],
    checkSize: "$100k-$1M",
    activity: "Miami early-stage fund",
    thesis: "Early-stage fund with a Miami footprint and broad technology appetite.",
    portfolioSignals: ["seed investing", "local founder network", "software companies"],
    contactPath: "Ask for a partner review after tightening traction and round narrative.",
    sourceLabels: ["Miami seed fund", "Early-stage focus"],
  },
  {
    id: "lab-ventures",
    name: "LAB Ventures",
    firm: "LAB Ventures",
    role: "Venture builder",
    initials: "LAB",
    color: "#D9870E",
    location: "Miami, FL",
    geography: "Local",
    stages: ["Validation / angel", "Pre-seed", "Seed"],
    sectors: ["Marketplace", "Proptech", "Consumer", "SaaS", "Fintech"],
    checkSize: "$25k-$500k",
    activity: "Venture studio and local builder",
    thesis: "Miami venture builder and early investor focused on company creation and market validation.",
    portfolioSignals: ["venture studio support", "marketplace playbooks", "local validation"],
    contactPath: "Frame the ask around validation, distribution, and local operator support.",
    sourceLabels: ["Miami venture studio", "Validation support"],
  },
  {
    id: "ocean-azul",
    name: "Ocean Azul Partners",
    firm: "Ocean Azul Partners",
    role: "Early-stage fund",
    initials: "OAP",
    color: "#3140CE",
    location: "Miami, FL",
    geography: "Local",
    stages: ["Seed", "Seed / Series A", "Series A-ready"],
    sectors: ["Enterprise", "SaaS", "Healthcare", "Fintech", "AI"],
    checkSize: "$500k-$3M",
    activity: "Miami early-stage investor",
    thesis: "Early-stage technology investor with Miami presence and enterprise software interest.",
    portfolioSignals: ["enterprise software", "seed to Series A", "B2B traction"],
    contactPath: "Lead with enterprise readiness, customer proof, and the next financing milestone.",
    sourceLabels: ["Miami VC", "Enterprise software"],
  },
  {
    id: "endeavor-miami",
    name: "Endeavor Miami",
    firm: "Endeavor Miami",
    role: "Founder network",
    initials: "EM",
    color: "#DB4444",
    location: "Miami, FL",
    geography: "Local",
    stages: ["Seed", "Seed / Series A", "Series A-ready"],
    sectors: ["SaaS", "Consumer", "Fintech", "Marketplace", "Healthcare"],
    checkSize: "Network access",
    activity: "High-growth founder network",
    thesis: "Founder network that can unlock mentor, operator, and investor access for scale-up companies.",
    portfolioSignals: ["mentor network", "operator intros", "high-growth founders"],
    contactPath: "Ask for mentor feedback and investor routing once traction metrics are clear.",
    sourceLabels: ["Miami founder network", "Warm intro path"],
  },
  {
    id: "las-olas-vc",
    name: "Las Olas Venture Capital",
    firm: "Las Olas VC",
    role: "B2B seed fund",
    initials: "LO",
    color: "#475569",
    location: "Fort Lauderdale, FL",
    geography: "Regional",
    stages: ["Pre-seed", "Seed", "Seed / Series A"],
    sectors: ["SaaS", "Enterprise", "AI", "Fintech", "Cybersecurity"],
    checkSize: "$500k-$2M",
    activity: "South Florida B2B fund",
    thesis: "South Florida seed fund focused on B2B software and enterprise technology.",
    portfolioSignals: ["B2B SaaS", "enterprise motion", "regional capital"],
    contactPath: "Lead with ICP, sales motion, and why the next round is seed-ready.",
    sourceLabels: ["South Florida VC", "B2B software"],
  },
  {
    id: "ps27-ventures",
    name: "PS27 Ventures",
    firm: "PS27 Ventures",
    role: "Seed investor",
    initials: "PS",
    color: "#7C3AED",
    location: "Jacksonville, FL",
    geography: "Regional",
    stages: ["Pre-seed", "Seed"],
    sectors: ["SaaS", "Healthtech", "Fintech", "Ecommerce", "Consumer"],
    checkSize: "$100k-$1M",
    activity: "Florida seed investor",
    thesis: "Florida-based seed investor backing early technology companies across the Southeast.",
    portfolioSignals: ["Southeast startups", "seed capital", "founder support"],
    contactPath: "Use the Florida ecosystem angle and ask for fit feedback before a formal pitch.",
    sourceLabels: ["Florida seed fund", "Southeast network"],
  },
  {
    id: "tampabay-ventures",
    name: "TampaBay.Ventures",
    firm: "TampaBay.Ventures",
    role: "Regional VC",
    initials: "TB",
    color: "#0891B2",
    location: "Tampa Bay, FL",
    geography: "Regional",
    stages: ["Seed", "Seed / Series A"],
    sectors: ["SaaS", "Enterprise", "Healthcare", "Fintech", "AI"],
    checkSize: "$250k-$2M",
    activity: "Florida software investor",
    thesis: "Regional fund focused on technology companies with Florida and Southeast relevance.",
    portfolioSignals: ["software companies", "regional ecosystems", "seed rounds"],
    contactPath: "Lead with category, traction, and Florida talent or customer-market connection.",
    sourceLabels: ["Florida VC", "Software focus"],
  },
  {
    id: "refresh-miami",
    name: "Refresh Miami",
    firm: "Refresh Miami",
    role: "Community access",
    initials: "RM",
    color: "#F97316",
    location: "Miami, FL",
    geography: "Local",
    stages: ["Validation / angel", "Pre-seed", "Seed"],
    sectors: ["SaaS", "Consumer", "Marketplace", "Fintech", "AI"],
    checkSize: "Intro network",
    activity: "Miami tech community",
    thesis: "Local community channel for founder visibility, warm intros, and investor discovery.",
    portfolioSignals: ["founder visibility", "event network", "local investor access"],
    contactPath: "Use as an intro channel: share the raise blurb and ask who locally should see it.",
    sourceLabels: ["Miami community", "Intro channel"],
  },
];
